services:
  ems_db:
    image: 'postgres'
    env_file:
      - .env.dev
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_DB=${DB_NAME}
  ems:
    build: .
    env_file:
      - .env.dev
    ports:
      - '${PORT}:${PORT}'
    environment:
      - DB_HOST=ems_db
      - DB_PORT=${DB_PORT}
    volumes:
      - .:/app
    depends_on:
      - ems_db
    links:
      - ems_db
